language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ep-ciproject' ]; then cd .. && eval "mv $currentfolder generator-ep-ciproject" && cd generator-ep-ciproject; fi
